### ISSUE TITLE
$this->until() in worker is always returning false so 'work' doesn't ever run

### ISSUE THREAD

**Issue by DustinYoder** [nicholasnet/QueueBundle#20]
I removed the $this->until() === false part of the statement
return ! (($this->manager->isDownForMaintenance() && ! $options->force) || $this->paused || $this->until() === false);

This allowed me to run idb_queue:work from symfony console and get jobs processed.  Otherwise, with the statement included, it would simply pause and stay paused.  What could make that happen?  It seems as though until() is just dispatching a 'looping' event and if nothing is listening it just pauses the work queue.  Is that correct?

**Comment by lsimeonov** [comment]
Ran into the same issue. Created a PR #22 with the fix and some tests on the method

**Comment by nicholasnet** [comment]
Sorry for the delay I was out. I will look into this one soon. Thank you.
